# Generated by Django 5.0.4 on 2024-09-04 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_userpayment_guest_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='stripeCardId',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='stripeCustomerId',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='stripeSubscriptionId',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='payment_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_checkout_id', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
