# Generated by Django 5.0.4 on 2024-09-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_active_guestemail_is_active_and_more'),
        ('payment', '0003_remove_userpayment_card_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_bool', models.BooleanField(default=False)),
                ('stripe_checkout_id', models.CharField(max_length=500)),
                ('guest_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.guestemail')),
            ],
        ),
    ]
