# Generated by Django 5.0.4 on 2024-05-30 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
