# Generated by Django 5.0.4 on 2024-06-29 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_remove_anuncio_imagem_remove_anuncio_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
